Differential Gauge
toorshia/justgage pull request #380
Opened 2022-11-28 13:40 UTC by leemind

Use config 'differential' and min must == -max (e.g. -50 & +50)

2022-11-28 16:21 UTC, robertsLando commented on justgage.js
> +        //console.log(`Value: ${value} So: ${So} Si: ${Si}`)
Remove comments

2022-11-28 16:21 UTC, robertsLando commented on justgage.js
> +        //console.log(path)
Same

2022-11-28 16:21 UTC, robertsLando commented on justgage.js
> +    console.log("animate?",rvl)
Same

2022-11-30 15:58 UTC, leemind commented
> Also please add the example to: https://github.com/toorshia/justgage/tree/master/docs/examples
> 
> name it `differential.html`

Done

2022-11-30 17:02 UTC, robertsLando commented
Fixes #345

2022-11-30 17:03 UTC, robertsLando requested changes
Please run `npm run lint-fix` command to fix lint issues

2022-12-01 07:39 UTC, merged